version: '3.7'

services:
  node-server:
    container_name: yearn-finance-container
    image: yearn-finance-image
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - name=value
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096
      - REACT_APP_ALCHEMY_API_KEY=${REACT_APP_ALCHEMY_API_KEY}
      - REACT_APP_ALLOW_DEV_MODE=${REACT_APP_ALLOW_DEV_MODE}
      - REACT_APP_BLOCKNATIVE_KEY=${REACT_APP_BLOCKNATIVE_KEY}
      - REACT_APP_ETHERSCAN_API_KEY=${REACT_APP_ETHERSCAN_API_KEY}
      - REACT_APP_FORTMATIC_KEY=${REACT_APP_FORTMATIC_KEY}
      - REACT_APP_PORTIS_KEY=${REACT_APP_PORTIS_KEY}
      - REACT_APP_YEARN_SUBGRAPH_KEY=${REACT_APP_YEARN_SUBGRAPH_KEY}
      - REACT_APP_ZAPPER_API_KEY=${REACT_APP_ZAPPER_API_KEY}
    expose:
      - '80'
    ports:
      - '80:80'
